# Generated by Django 2.0.2 on 2019-02-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190220_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_post_related_+', to='posts.Post'),
        ),
    ]
